-- phpMyAdmin SQL Dump
-- version 4.7.4
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le :  ven. 13 avr. 2018 à 19:35
-- Version du serveur :  5.7.19
-- Version de PHP :  5.6.31

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `pokedek`
--

-- --------------------------------------------------------

--
-- Structure de la table `pokemon`
--

DROP TABLE IF EXISTS `pokemon`;
CREATE TABLE IF NOT EXISTS `pokemon` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nom` text NOT NULL,
  `type` text NOT NULL,
  `description` longtext NOT NULL,
  `attaque_rapide` text NOT NULL,
  `attaque_special` text NOT NULL,
  `faiblesse` text NOT NULL,
  `resistance` text NOT NULL,
  `immunite` text NOT NULL,
  `link_img` text NOT NULL,
  `link_card` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=152 DEFAULT CHARSET=latin1;

--
-- Déchargement des données de la table `pokemon`
--

INSERT INTO `pokemon` (`id`, `nom`, `type`, `description`, `attaque_rapide`, `attaque_special`, `faiblesse`, `resistance`, `immunite`, `link_img`, `link_card`) VALUES
(1, 'Bulbizarre', 'Plante, Poison', 'Bublbizarre passe son temps à faire la sieste sous le soleil. Il y a une graine sur son dos. Il absorbe les rayons du soleil pour faire doucement pousser la graine.', 'Charge, Fouet Lianes', 'Bomb-Beurk, Canon Graine, Mégafouet', 'Feu, Glace, Psy, Vol', 'Combat, Eau, Électrik, Fée, Normal', 'Aucune', 'img/pokemon/1.png', 'img/card/1.png'),
(2, 'Herbizarre', 'Plante,  Poison', 'Un bourgeon a poussé sur le dos de ce Pokémon. Pour en supporter le poids, Herbizarre a dû se muscler les pattes. Lorsquil commence à se prélasser au soleil, ça signifie que son bourgeon va éclore, donnant naissance à une fleur.', 'TranchHerbe, Fouet Lianes', 'Bomb-Beurk, Lance-Soleil, Mégafouet', 'Feu, Glace, Psy, Vol', 'Combat, Eau, Électrik, Fée, Normal', 'Aucune', 'img/pokemon/2.png', 'img/card/2.png'),
(3, 'Florizarre', 'Plante,  Poison', 'Une belle fleur se trouve sur le dos de Florizarre. Elle prend une couleur vive lorsquelle est bien nourrie et bien ensoleillée. Le parfum de cette fleur peut apaiser les gens.\r\n', 'TranchHerbe, Fouet Lianes', 'Bomb-Beurk, Lance-Soleil, Temête Florale', 'Feu, Glace, Psy, Vol', 'Combat, Eau, Électrik, Fée, Normal', 'Aucune', 'img/pokemon/3.png', 'img/card/3.png'),
(4, 'Salamèche', 'Feu', 'La flamme qui brûle au bout de sa queue indique lhumeur de ce Pokémon. Elle vacille lorsque Salamèche est content. En revanche, lorsquil sénerve, la flamme prend de limportance et brûle plus ardemment.', 'Griffe, Flamèche', 'Rebondifeu, Lance-Flammes, Nitrocharge', 'Eau, Roche, Sol', 'Acier, Fée, Feu, Glace, Insecte, Plante', 'Aucune', 'img/pokemon/4.png', 'img/card/4.png'),
(5, 'Reptincelle', 'Feu', 'Reptincel lacère ses ennemis sans pitié grâce à ses griffes acérées. Sil rencontre un ennemi puissant, il devient agressif et la flamme au bout de sa queue sembrase et prend une couleur bleu clair.', 'Crocs Feu, Flamèche', 'Rebondifeu, Lance-Flammes, Poing de feu', ' Eau, Roche, Sol', 'Acier, Fée, Feu, Glace, Insecte, Plante', 'Aucune', 'img/pokemon/5.png', 'img/card/5.png'),
(6, 'Dracaufeu', 'Feu,  Vol', 'En plus de pouvoir le rencontrer au hasard dune promenade, Dracaufeu est disponible en faisant évoluer Reptincel pour 100 bonbons', 'Lame dAir, Danse Flamme', 'Dracogriffe, Surchauffe, Déflagration', ' Eau, Roche, Électrik', 'Acier, Fée, Feu, Combat, Insecte, Plante', 'Aucune', 'img/pokemon/6.png', 'img/card/6.png'),
(7, 'Carapuce', 'Eau', 'La carapace de Carapuce ne sert pas quà le protéger. La forme ronde de sa carapace et ses rainures lui permettent daméliorer son hydrodynamisme. Ce Pokémon nage extrêmement vite.', 'Charge, Écume', 'Aqua-Jet, Hydroqueue, Vibraqua', 'Électrik, Plante', 'Acier, Eau, Feu, Glace', 'Aucune', 'img/pokemon/7.png', 'img/card/7.png'),
(8, 'Carabaffe', 'Eau', 'Carabaffe a une large queue recouverte dune épaisse fourrure. Elle devient de plus en plus foncée avec lâge. Les éraflures sur la carapace de ce Pokémon témoignent de son expérience au combat.', 'Morsure, Pistolet à O', 'Aqua-Jet, Hydrocanon, Laser Glace', 'Électrik, Plante', 'Acier, Eau, Feu, Glace', 'Aucune', 'img/pokemon/8.png', 'img/card/8.png'),
(9, 'Tortank', 'Eau', 'Tortank dispose de canons à eau émergeant de sa carapace. Ils sont très précis et peuvent envoyer des balles deau capables de faire mouche sur une cible située à plus de 50 m.', 'Morsure, Pistolet à O', 'Luminocanon, Hydrocanon, Laser Glace', 'Électrik, Plante', 'Acier, Eau, Feu, Glace', 'Aucune', 'img/pokemon/9.png', 'img/card/9.png'),
(10, 'Chenipan', 'Insecte', 'Chenipan a un appétit dogre. Il peut engloutir des feuilles plus grosses que lui. Les antennes de ce Pokémon dégagent une odeur particulièrement entêtante.', 'Charge, Piqûre', 'Lutte', 'Feu, Roche, Vol', 'Combat, Plante, Sol', 'Aucune', 'img/pokemon/10.png', 'img/card/10.png'),
(11, 'Chrysacier', 'Insecte', 'La carapace protégeant ce Pokémon est dure comme du métal. Chrysacier ne bouge pas beaucoup. Il reste immobile pour préparer les organes à lintérieur de sa carapace en vue dune évolution future.', 'Charge, Piqûre', 'Lutte', 'Feu, Roche, Vol', 'Combat, Plante, Sol', 'Aucune', 'img/pokemon/11.png', 'img/card/11.png'),
(12, 'Papillusion', 'Insecte,  Vol', 'Papilusion est très doué pour repérer le délicieux nectar quil butine dans les fleurs. Il peut détecter, extraire et transporter le nectar de fleurs situées à plus de 10 km de son nid.', 'Choque Mental, Survinsecte', 'Psyko, Bourdon, Rayon Signal', 'Feu, Roche, Glace, Électrik', 'Combat, Plante, Insecte', 'Sol', 'img/pokemon/12.png', 'img/card/12.png'),
(13, 'Aspicot', 'Insecte, Poison', 'Lodorat dAspicot est extrêmement développé. Il lui suffit de renifler ses feuilles préférées avec son gros appendice nasal pour les reconnaître entre mille.\r\n', 'Piqûre, Dard-Venin', 'Lutte', 'Feu, Poison, Roche, Vol', 'Combat, Fée, Insecte, Plante, Poison', 'Aucune', 'img/pokemon/13.png', 'img/card/13.png'),
(14, 'Coconfort', 'Insecte, Poison', 'Coconfort est la plupart du temps immobile et reste accroché à un arbre. Cependant, intérieurement, il est très actif, car il se prépare pour sa prochaine évolution. En touchant sa carapace, on peut sentir sa chaleur', 'Piqûre, Dard-Venin', 'Lutte', 'Feu, Poison, Roche, Vol', 'Combat, Fée, Insecte, Plante, Poison', 'Aucune', 'img/pokemon/14.png', 'img/card/14.png'),
(15, 'Dardagnan', 'Insecte, Poison', 'Dardargnan est extrêmement possessif. Il vaut mieux ne pas toucher son nid si on veut éviter davoir des ennuis. Lorsquils sont en colère, ces Pokémon attaquent en masse.', 'Harcèlement, Direct Toxic', 'Aéropic, Bomb-Beurk, Plaie-Croix', 'Feu, Poison, Roche, Vol', 'Combat, Fée, Insecte, Plante, Poison', 'Aucune', 'img/pokemon/15.png', 'img/card/15.png'),
(16, 'Roucool', 'Normal,  Vol', 'Roucool a un excellent sens de lorientation. Il est capable de retrouver son nid sans jamais se tromper, même sil est très loin de chez lui et dans un environnement quil ne connaît pas.', 'Charge, Vive-Attaque', 'Ourgan, Aéropique, TranchAir', 'Électrik, Glace, Roche', 'Insecte, Plante', 'Sol, Spectre', 'img/pokemon/16.png', 'img/card/16.png'),
(17, 'Roucoups', 'Normal,  Vol', '', '', '', 'Électrik, Glace, Roche', 'Insecte, Plante', 'Sol, Spectre', 'img/pokemon/17.png', 'img/card/17.png'),
(18, 'Roucarnage', 'Normal,  Vol', 'Ce Pokémon est doté dun plumage magnifique et luisant. Bien des Dresseurs sont captivés par la beauté fatale de sa huppe et décident de choisir Roucarnage comme leur Pokémon favori.', 'LameAir, Aile dAcier', 'Vent Violent, Aéropique, Rapace', 'Électrik, Glace, Roche', 'Insecte, Plante', 'Sol, Spectre', 'img/pokemon/18.png', 'img/card/18.png'),
(19, 'Rattata', 'Normal', 'Rattata est extrêmement prudent. Même lorsquil est endormi, il fait pivoter ses oreilles pour écouter autour de lui. En ce qui concerne son habitat, il nest vraiment pas difficile. Il peut faire son nid nimporte où.', 'Charge, Vive-Attaque', 'Tunnel, Croc de Mort, Plaquage', 'Combat', 'Aucune', 'Spectre', 'img/pokemon/19.png', 'img/card/19.png'),
(20, 'Rattatac', 'Normal', 'Les crocs robustes de Rattatac poussent constamment. Pour éviter quils raclent le sol, il se fait les dents sur des cailloux ou des troncs darbre. Il lui arrive même de ronger les murs des maisons.', 'Morsure, Vive-Attaque', 'Tunnel, Croc de Mort, Ultralaser', 'Combat', 'Aucune', 'Spectre', 'img/pokemon/20.png', 'img/card/20.png'),
(21, 'Piafabec', 'Normal,  Vol', 'Piafabec crie tellement fort quil peut être entendu à 1 km de distance. Ces Pokémon se préviennent dun danger en entonnant une mélopée très aiguë, quils se renvoient les uns les autres, comme un écho.', 'Vive-Attaque, Picpic', 'Aéropique, Piqué, Bec Vrille', 'Électrik, Glace, Roche', 'Insecte, Plante', 'Sol, Spectre', 'img/pokemon/21.png', 'img/card/21.png'),
(22, 'Rapasdepic', 'Normal, Vol', 'En plus de pouvoir le rencontrer au hasard dune promenade, Rapasdepic est disponible en faisant évoluer Piafabec pour 50 bonbons.', 'Aile dAcier, Picpic', 'Aéropique, Piqué, Tunnelier', 'Électrik, Glace, Roche', 'Insecte, Plante', 'Sol, Spectre', 'img/pokemon/22.png', 'img/card/22.png'),
(23, 'Abo', 'Poison', 'Abo senroule en spirale pour dormir. Sa tête reste relevée de telle sorte que cette position lui permette de réagir rapidement si une menace survenait.', 'Acide, Dard-Venin', 'Crochet Venin, Bomb-Beurk, Ligotage', 'Psy, Sol', 'Combat, Fée, Insecte, Plante, Poison', 'Aucune', 'img/pokemon/23.png', 'img/card/23.png'),
(24, 'Arbok', 'Poison', 'Ce Pokémon doté dune force extraordinaire peut étrangler ses proies avec son corps. Il peut même écraser des tonneaux métalliques. Une fois sous létreinte dArbok, il est impossible de lui échapper.', 'Acide, Morsure', 'Détricanon, Cradovague, Vibroscure', 'Psy, Sol', 'Combat, Fée, Insecte, Plante, Poison', 'Aucune', 'img/pokemon/24.png', 'img/card/24.png'),
(25, 'Pikachu', 'Élektric', 'Chaque fois que Pikachu découvre quelque chose de nouveau, il envoie un arc électrique. Lorsquon tombe sur une Baie carbonisée, ça signifie sans doute quun de ces Pokémon a envoyé une charge trop forte.', 'Éclair, Vive-Attaque', 'Tonnerre, Coup dJus, Éclair Fou', 'Sol', 'Acier, Électrik, Vol', 'Aucune', 'img/pokemon/25.png', 'img/card/25.png'),
(26, 'Raichu', 'Élektric', 'En plus de pouvoir le rencontrer au hasard dune promenade, Raichu est disponible en faisant évoluer Pikachu pour 50 bonbons.', 'Change Éclair, Étincelle', 'Casse-Brique, Poing-Éclair, Éclair Fou', 'Sol', 'Acier, Électrik, Vol', 'Aucune', 'img/pokemon/26.png', 'img/card/26.png'),
(27, 'Sabelette', 'Sol', 'Le corps de Sabelette lui permet déconomiser leau quil absorbe, afin de survivre longtemps dans le désert. Ce Pokémon senroule sur lui-même pour se protéger de ses ennemis.', 'Griffe, Tir de Boue', 'Tunnel, Éboulement, Tourbi-Sable', 'Eau, Feu, Plante', 'Poison, Roche', 'Aucune', 'img/pokemon/27.png', 'img/card/27.png'),
(28, 'Sablaireau', 'Sol', 'Le corps de Sablaireau est recouvert de pointes très dures, qui sont des extensions de sa peau. Une fois par an, ce Pokémon mue et les vieilles pointes tombent, remplacées par de nouvelles.', 'Griffe Acier, Tir de Boue', 'Tomberoche, Piéstisol, Séisme', 'Eau, Feu, Plante', 'Poison, Roche', 'Élektric', 'img/pokemon/28.png', 'img/card/28.png'),
(29, 'Nidoran (femelle)', 'Poison', 'Nidoran (femelle) est couvert de pointes qui sécrètent un poison puissant. On pense que ce petit Pokémon a développé ces pointes pour se défendre. Lorsquil est en colère, une horrible toxine sort de sa corne.', 'Dard-Venin, Morsure', 'Crochetvenin, Bomb-Beurk, Plaquage', 'Psy, Sol', 'Combat, Fée, Insecte, Plante, Poison', 'Aucune', 'img/pokemon/29.png', 'img/card/29.png'),
(30, 'Nidorina ', 'Poison', 'Lorsquun Nidorina (femelle) est avec ses amis ou sa famille, il replie ses pointes pour ne pas blesser ses proches. Ce Pokémon devient vite nerveux lorsquil est séparé de son groupe.', 'Dard-Venin, Morsure', 'Crochetvenin, Bomb-Beurk, Tunnel', 'Psy, Sol', 'Combat, Fée, Insecte, Plante, Poison', 'Aucune', 'img/pokemon/30.png', 'img/card/30.png'),
(31, 'Nidoqueen', 'Poison, Sol', 'Le corps de Nidoqueen (femelle) est protégé par des écailles extrêmement dures. Il aime envoyer ses ennemis voler en leur fonçant dessus. Ce Pokémon utilise toute sa puissance lorsquil protège ses petits.', 'Direct Toxik, Morsure', 'Lame de Roc, Cradovague, Séisme', 'Eau, Glace, Psy, Sol', 'Combat, Fée, Insecte, Roche', 'Élektric', 'img/pokemon/31.png', 'img/card/31.png'),
(32, 'Nirdoran (mâle)', 'Poison', 'Nidoran (mâle) a développé des muscles pour bouger ses oreilles. Ainsi, il peut les orienter à sa guise. Ce Pokémon peut entendre le plus discret des bruits.', 'Dard-Venin, Picpic', 'KoudKorn, Bomb-Beurk, Plaquage', 'Psy, Sol', 'Combat, Fée, Insecte, Plante, Poison', 'Aucune', 'img/pokemon/32.png', 'img/card/32.png'),
(33, 'Nidorino', 'Poison', 'Nidorino dispose dune corne plus dure que du diamant. Sil sent une présence hostile, toutes les pointes de son dos se hérissent dun coup, puis il défie son ennemi.', 'Direct Toxik, Dard-Venin', 'KoudKorn, Bomb-Beurk, Tunnel', 'Psy, Sol', 'Combat, Fée, Insecte, Plante, Poison', 'Aucune', 'img/pokemon/33.png', 'img/card/33.png'),
(34, 'Nidoking', 'Poison, Sol', 'Lépaisse queue de Nidoking est dune puissance incroyable. En un seul coup, il peut renverser une tour métallique. Lorsque ce Pokémon se déchaîne, plus rien ne peut larrêter.', 'Direct-Toxik, Queue de Fer', 'Mégacorne, Séisme, Cradovague', 'Eau, Glace, Psy, Sol', 'Combat, Fée, Insecte, Roche', 'Élektric', 'img/pokemon/34.png', 'img/card/34.png'),
(35, 'Mélofée', 'Fée', 'Les nuits de pleine lune, des groupes de ces Pokémon sortent jouer. Lorsque laube commence à poindre, les Mélofée fatigués rentrent dans leur retraite montagneuse et vont dormir, blottis les uns contre les autres.', 'PsykoudBoule, ÉcrasFace', 'Plaquage, Voix Enjôleuse, Pouvoir Lunaire', 'Acier, Poison', 'Combat, Insecte, Ténèbres', 'Dragon', 'img/pokemon/35.png', 'img/card/35.png'),
(36, 'Mélodelf', 'Fée', 'Les Mélodelfe se déplacent en sautant doucement, comme sils volaient. Leur démarche légère leur permet même de marcher sur leau. On raconte quils se promènent sur les lacs, les soirs où la lune est claire.', 'PsykoudBoule, Rayon Chargé', 'Psycho, Éclat Magique, Pouvoir Lunaire', 'Acier, Poison', 'Combat, Insecte, Ténèbres', 'Dragon', 'img/pokemon/36.png', 'img/card/36.png'),
(37, 'Goupix', 'Feu', 'À sa naissance, Goupix a une queue blanche. Cette queue se divise en six si le Pokémon reçoit de lamitié de la part de son Dresseur. Les six queues sont courbées et magnifiques.', 'Vive-Attaque, Flammèche', 'Lance-Flammes, Plaquage, Nitrocharge', 'Eau, Roche, Sol', 'Acier, Fée, Feu, Glace, Insecte, Plante', 'Aucune', 'img/pokemon/37.png', 'img/card/37.png'),
(38, 'Feunard', 'Feu', 'Feunard peut envoyer un inquiétant rayon avec ses yeux rouge vif pour prendre le contrôle de lesprit de son ennemi. On raconte que ce Pokémon peut vivre 1 000 ans.', 'Feinte, Danse-Flamme', 'Lance-Soleil, Canicule, Surchauffe', 'Eau, Roche, Sol', 'Acier, Fée, Feu, Glace, Insecte, Plante', 'Aucune', 'img/pokemon/38.png', 'img/card/38.png'),
(39, 'Rondoudou', 'Fée,  Normal', 'Rondoudou utilise ses cordes vocales pour ajuster librement la longueur donde de sa voix. Cela permet à ce Pokémon de chanter en utilisant une longueur donde qui endort ses ennemis.', 'Feinte, ÉcrasFace', 'Voix Enjôleuse, Gyroballe, Éclat Magique', 'Acier, Poison', 'Insecte, Ténèbres', 'Dragon, Spectre', 'img/pokemon/39.png', 'img/card/39.png'),
(40, 'Grodoudou', 'Fée,  Normal', 'Grodoudou a des yeux immenses et écarquillés. La surface de ses yeux est couverte dune fine couche de larmes. Si de la poussière est projetée dans les yeux de ce Pokémon, elle est rapidement évacuée.', 'Feinte, ÉcrasFace', 'Éclat Magique, Ultralaser, Calinerie', 'Acier, Poison', 'Insecte, Ténèbres', 'Dragon, Spectre', 'img/pokemon/40.png', 'img/card/40.png'),
(41, 'Nosferapti', 'Poison, Vol', 'Nosferapti reste calme et immobile dans un coin sombre pendant la journée. En effet, une exposition trop longue à la lumière du soleil lui brûle légèrement la peau.', 'Vive-Attaque, Morsure', 'Corchet Venin, TranchAir, Météores', 'Glace, Roche, Psy, Électrik', 'Sol, Poison, Fée, Combat, Plante, Insecte', 'Aucune', 'img/pokemon/41.png', 'img/card/41.png'),
(42, 'Nosferalto', 'Poison, Vol', 'Nosferalto adore boire le sang des créatures vivantes. Il est particulièrement actif pendant les nuits noires. Ce Pokémon se balade dans les cieux étoilés, à la recherche de sang frais.\"', 'Cru-Aile, Morsure', 'Corchet Venin, TranchAir, BallOmbre', 'Glace, Roche, Psy, Électrik', 'Sol, Poison, Fée, Combat, Plante, Insecte', 'Aucune', 'img/pokemon/42.png', 'img/card/42.png'),
(43, 'Mystherbe', 'Plante,  Poison', 'Pendant la journée, Mystherbe senterre dans le sol pour absorber avec son corps tout entier les nutriments présents dans la terre. Plus le sol est fertile, plus ses feuilles sont brillantes.', 'TranchHerbe, Acide', 'Canon Graine, Bomb-Beurk, Pouvoir Lunaire', 'Feu, Glace, Psy, Vol', 'Combat, Eau, Électrik, Fée, Plante', 'Aucune', 'img/pokemon/43.png', 'img/card/43.png'),
(44, 'Ortide', 'Plante,  Poison', 'La plupart du temps, Ortide dégage un parfum immonde du pistil de sa fleur. Lorsquil se sent en danger, la puanteur est encore pire. Lorsque ce Pokémon se sent bien et en sécurité, il ne dégage aucune odeur nauséabonde.', 'TranchHerbe, Acide', 'Tempête Florale, Bomb-Beurk, Pouvoir Lunaire', 'Feu, Glace, Psy, Vol', 'Combat, Eau, Électrik, Fée, Plante', 'Aucune', 'img/pokemon/44.png', 'img/card/44.png'),
(45, 'Rafflesia', 'Plante,  Poison', 'Le pollen toxique de Rafflesia déclenche daffreuses réactions allergiques. Cest pourquoi il est conseillé de ne jamais sapprocher des jolies fleurs trouvées dans la jungle, même lorsquelles sont magnifiques.', 'TranchHerbe, Acide', 'Tempête Florale, Lance-Soleil, Pouvoier Lunaire', 'Feu, Glace, Psy, Vol', 'Combat, Eau, Électrik, Fée, Plante', 'Aucune', 'img/pokemon/45.png', 'img/card/45.png'),
(46, 'Paras', 'Insecte,  Plante', 'Paras accueille des champignons parasites appelés tochukaso qui poussent sur son dos. Ils grandissent grâce aux nutriments trouvés sur le dos de ce Pokémon Insecte. Ils peuvent rallonger lespérance de vie.', 'Griffe, Piqûre', 'Poison-Croix, Plaie-Croix, Canon Graine', 'Vol, Poison, Roche, Insecte, Feu, Glace', 'Combat, Sol, Eau, Plante, Électrik', 'Aucune', 'img/pokemon/46.png', 'img/card/46.png'),
(47, 'Parasect', 'Insecte,  Plante', 'On sait que les Parasect vivent en groupe dans les grands arbres et se nourrissent des nutriments contenus dans le tronc et les racines. Lorsquun arbre infesté meurt, ils se précipitent vers le prochain.', 'Taillade, Survinsecte', 'Poison-Croix, Plaie-Croix, Lance-Soleil', 'Vol, Poison, Roche, Insecte, Feu, Glace', 'Combat, Sol, Eau, Plante, Électrik', 'Aucune', 'img/pokemon/47.png', 'img/card/47.png'),
(48, 'Mimitoss', 'Insecte,  Poison', 'On raconte que Mimitoss a évolué avec une fourrure de poils fins et drus qui protège son corps tout entier. Il est doté de grands yeux capables de repérer ses proies, même minuscules.', 'Piqûre, Choc Mental', 'Crochet Venin, Rafale Psy, Rayon Signal', 'Vol, Roche, Feu, Psy', 'Combat, Poison, Insecte, Plante, Fée', 'Aucune', 'img/pokemon/48.png', 'img/card/48.png'),
(49, 'Aéromite', 'Insecte,  Poison', 'Aéromite est un Pokémon nocturne, il ne sort donc que la nuit. Ses proies préférées sont les petits insectes qui se rassemblent autour des réverbères, attirés par la lumière.', 'Harcèlement, Choc Mental', 'Psyko, Bourdon, Vent Argenté', 'Vol, Roche, Feu, Psy', 'Combat, Poison, Insecte, Plante, Fée', 'Aucune', 'img/pokemon/49.png', 'img/card/49.png'),
(50, 'Taupiqueur', 'Sol', 'Les Taupiqueur sont élevés dans la plupart des fermes. En effet, lorsque ce Pokémon creuse quelque part, le sol est comme labouré, prêt à recevoir les semences. On peut alors y planter de délicieux légumes.', 'Griffe, CoudBoue', 'Tunnel, Boue-Bombe, Tomberoche', 'Plante, Glace, Eau', 'Roche, Poison, Électrik', 'Aucune', 'img/pokemon/50.png', 'img/card/50.png'),
(51, 'Triopiqueur', 'Sol', 'Les Triopikeur sont en fait des triplés qui ont émergé du même corps. Cest pourquoi chaque triplé pense exactement comme les deux autres. Ils creusent inlassablement, dans une coopération parfaite.', 'Coup Bas, Coud’Boue', 'Séisme, Boue-Bombe, Lame de Roc', 'Eau, plante, glace', 'Poisson, roche', 'Electrik', 'img/pokemon/51.png', 'img/card/51.png'),
(52, 'Miaouss', 'Normal', 'Miaouss peut rentrer ses griffes dans ses pattes pour rôder gracieusement sans laisser de traces. Étrangement, ce Pokémon raffole des pièces dor qui brillent à la lumière.', 'Griffe, Morsure', 'Trancge nuit, Vibroscur, Tricherie', 'Combat', 'Aucune', 'Spectre', 'img/pokemon/52.png', 'img/card/52.png'),
(53, 'Persian', 'Normal', 'Persian a six grosses vibrisses qui lui donnent un air costaud et lui permettent de sentir les mouvements de lair pour savoir ce qui se trouve à proximité. Il devient docile lorsquon lattrape par les moustaches.', 'Griffe, feinte ', 'Rayon gemme, Câlinerie, Tricherie', 'Combat', 'Aucune', 'Spectre', 'img/pokemon/53.png', 'img/card/53.png'),
(54, 'Psykokwak', 'Eau', 'Psykokwak utilise un mystérieux pouvoir. Ce Pokémon peut générer des ondes cérébrales normalement observées chez les dormeurs. Cette découverte a lancé une polémique dans le milieu universitaire.', 'Pistolet à O, Psykoud’Boul', 'Rafale Psy, Hydroqueue, Coup-Croix', 'Plante, Electrik', 'Acier, Feu, Eau, Glace ', 'Aucune', 'img/pokemon/54.png', 'img/card/54.png'),
(55, 'Akwakwak', 'Eau', 'Les pattes avant et arrière palmées et le corps aérodynamique dAkwakwak lui donnent une vitesse effrayante. Ce Pokémon est bien plus rapide que les plus grands champions de natation.', 'Pistolet à O, Choc Mental ', 'Psyko, Hydrocanon, Laser Glace', 'Plante, Electrik', 'Acier, Feu, Eau, Glace ', 'Aucune', 'img/pokemon/55.png', 'img/card/55.png'),
(56, 'Férosinge', 'Combat', 'Lorsque Ferosinge commence à trembler et que sa respiration devient haletante, cela signifie quil est en colère. En outre, la moutarde lui monte au nez tellement vite quil est presque impossible déchapper à sa colère.', 'Poing karaté, Griffe', 'Coup croix, balayette, casse brique', 'Vol, Psy, Fée', 'Roche, insecte, Ténèbres', 'Aucune', 'img/pokemon/56.png', 'img/card/56.png'),
(57, 'Colossinge', 'Combat', 'Lorsque Colossinge devient furieux, sa circulation sanguine saccélère. Du coup, ses muscles sont encore plus puissants. En revanche, il devient bien moins intelligent.', 'Balayage, Riposte', 'Tranche nuit, Balyette, Close combat', 'Vol, Psy, Fée', 'Roche, insecte, Ténèbres', 'Aucune', 'img/pokemon/57.png', 'img/card/57.png'),
(58, 'Caninos', 'Feu', 'Caninos a un odorat très développé. Ce Pokémon noublie jamais un parfum, quel quil soit. Il utilise son puissant sens olfactif pour deviner les émotions des autres créatures vivantes.', 'Flamèche, Morsure', 'Roue de feu, plaquage, lance flamme', 'Sol, roche, eau', 'Insecte, acier, feu, plante, glace, feu', 'Aucune', 'img/pokemon/58.png', 'img/card/58.png'),
(59, 'Arcanin', 'Feu', 'Arcanin est célèbre pour son extraordinaire vitesse. On le dit capable de parcourir plus de 10 000 km en 24 h. Le feu qui fait rage à lintérieur du corps de ce Pokémon est la source de son pouvoir.', 'Crocs feu, aboiements', 'Déflagration, éclair fou, mâchouille', 'Sol, roche, eau', 'Insecte, acier, feu, plante, glace, feu', 'Aucune', 'img/pokemon/59.png', 'img/card/59.png'),
(60, 'Ptitard', 'Eau', 'Ptitard a une peau très fine. On peut même voir les entrailles en spirale de ce Pokémon à travers sa peau. Malgré sa finesse, cette peau est aussi très élastique. Même les crocs les plus acérés rebondissent dessus.', 'Ecume, tir de boue', 'Bulle dO, Boue-Bombe, plaquage', 'Plante, Electrik', 'Acier, Feu, Eau, Glace ', 'Aucune', 'img/pokemon/60.png', 'img/card/60.png'),
(61, 'Têtarte', 'Eau', 'La peau de Têtarte est toujours maintenue humide par un liquide huileux. Grâce à cette protection graisseuse, il peut facilement se glisser hors de létreinte de nimporte quel ennemi.', 'Ecume, tir de boue', 'Bulle dO, Boue-Bombe, Vibraqua', 'Plante, Electrik', 'Acier, Feu, Eau, Glace ', 'Aucune', 'img/pokemon/61.png', 'img/card/61.png'),
(62, 'Tartard', 'Eau', 'Les muscles solides et surdéveloppés de Tartard ne se fatiguent jamais, quels que soient les efforts quil produit. Ce Pokémon est tellement endurant quil peut traverser un océan à la nage avec une étonnante facilité.', 'Ecume, Eclate roc', 'Hydrocanon, Poing glace, Dynamopoing', 'Vol, Plante, Electrik, Psy, Fée', 'Roche, Insecte, Acier, Feu, Eau, Glace, Ténèbre', 'Aucune', 'img/pokemon/62.png', 'img/card/62.png'),
(63, 'Abra', 'Psy', 'Abra dort dix-huit heures par jour. Pourtant, il peut sentir la présence de ses ennemis, même endormi. Dans ce genre de situation, ce Pokémon se téléporte en lieu sûr.', 'Psykoud’Boul, Rayon chargé ', 'Choc psy, Rayon signal, Ball Ombre', 'Insecte, specte, Ténèbre', 'Combat, Psy', 'Aucune', 'img/pokemon/63.png', 'img/card/63.png'),
(64, 'Kadabra', 'Psy', 'Kadabra émet une onde alpha si particulière quelle vous donne mal à la tête. Seuls les gens avec un psychisme puissant peuvent espérer devenir Dresseur de ce Pokémon.', 'Coupe psycho, Choc Mental', 'Rafale psy, Eclat magique, Ball Ombre', 'Insecte, specte, Ténèbre', 'Combat, Psy', 'Aucune', 'img/pokemon/64.png', 'img/card/64.png'),
(65, 'Alakazam', 'Psy', 'Le cerveau dAlakazam grossit sans arrêt, si bien que sa tête devient trop lourde pour son cou. Ce Pokémon maintient sa tête relevée grâce à son pouvoir télékinétique.', 'Coupe psycho, Choc Mental', 'Exploforce, Prescience, BallOmbre', 'Insecte, specte, Ténèbre', 'Combat, Psy', 'Aucune', 'img/pokemon/65.png', 'img/card/65.png'),
(66, 'Machoc', 'Combat', 'Les muscles de Machoc sont spéciaux. Quels que soient les efforts quil produit, il na jamais de courbature. Ce Pokémon est assez puissant pour lancer une centaine dhommes adultes.', 'Poing Karaté, Eclate roc', 'Balayette, Casse-brique, Coup-Croix ', 'Vol, Psy, Fée', 'Roche, insecte, ténèbres', 'Aucune', 'img/pokemon/66.png', 'img/card/66.png'),
(67, 'Machopeur', 'Combat', 'Les muscles toniques de Machopeur sont durs comme de lacier. Ce Pokémon est si fort quil peut facilement soulever un sumo avec un seul doigt.', 'Poing karaté, balayage ', 'Sacrifice, Casse-brique, Dynamopoing', 'Vol, Psy, Fée', 'Roche, insecte, ténèbres', 'Aucune', 'img/pokemon/67.png', 'img/card/67.png'),
(68, 'Mackogneur', 'Combat', 'Mackogneur est capable de déplacer nimporte quelle masse. Cependant, ses bras semmêlent dès quil essaie de réaliser un travail délicat ou minutieux. Ce Pokémon a tendance à cogner dabord et à réfléchir ensuite.', 'Pisto-poing, Riposte', 'Close-combat, tacle lourd, Dynamopoing', 'Vol, Psy, Fée', 'Roche, insecte, ténèbres', 'Aucune', 'img/pokemon/68.png', 'img/card/68.png'),
(69, 'Chetifleur', 'Plante,  Poison', 'Le corps long et flexible de Chétiflor lui permet de se tordre et dosciller pour éviter tout type dattaque, même les plus puissantes. Ce Pokémon crache un fluide corrosif qui peut même dissoudre le fer.', 'Fouets lianes, Acide', 'Méga-fouet, Bomb Beurk, Ligotage', 'Vol, Feu, Psy, Glace', 'Combat, Eau, Plante, Electrick, Fée', 'Aucune', 'img/pokemon/69.png', 'img/card/69.png'),
(70, 'Boustiflor', 'Plante,  Poison', 'Boustiflor est doté dun gros crochet. La nuit, ce Pokémon saccroche à une branche pour sendormir. Quand il a un sommeil agité, il se réveille par terre.', 'Acide, Balle graine', 'Méga-fouet, Bomb Beurk, Canon Graine', 'Vol, Feu, Psy, Glace', 'Combat, Eau, Plante, Electrick, Fée', 'Aucune', 'img/pokemon/70.png', 'img/card/70.png'),
(71, 'Empiflor', 'Plante,  Poison', 'Empiflor est doté dune longue liane qui part de sa tête. Cette liane se balance et remue comme un animal pour attirer ses proies. Lorsque lune delles sapproche un peu trop près, ce Pokémon lavale entièrement.', 'Acide, Tranchherbe', 'Lame-Feuille, Bomb beurk, Lance soleil', 'Vol, Feu, Psy, Glace', 'Combat, Eau, Plante, Electrick, Fée', 'Aucune', 'img/pokemon/71.png', 'img/card/71.png'),
(72, 'Tentacool', 'Eau,  Poison', 'Le corps de Tentacool est principalement aqueux. Si on le retire de leau, il se déshydrate complètement. Si cela arrive, il suffit de le replonger dans un liquide pour quil reprenne sa forme normale.', 'Ecume, DardVenin', 'Bulle dO, vibraqua, Ligotage', 'Sol, Electrick, Psy', 'Combat, Poison, Insecte, Plante, Feu, Eau, Glace, Fée', 'Aucune', 'img/pokemon/72.png', 'img/card/72.png'),
(73, 'Tentacruel', 'Eau,  Poison', 'Tentacruel a deux gros globes sur la tête. Les globes silluminent lorsquil va envoyer un violent rayon dultrasons. Lorsque ce Pokémon se déchaîne, il crée dénormes vagues autour de lui.', 'Acide, DardVenin', 'Hydrocanon, Crdovague, Blizzard', 'Sol, Electrick, Psy', 'Combat, Poison, Insecte, Plante, Feu, Eau, Glace, Fée', 'Aucune', 'img/pokemon/73.png', 'img/card/73.png'),
(74, 'Racaillou', 'Roche,  Sol', 'Lorsquun Racaillou prend de lâge, ses bords sébrèchent et susent, ce qui lui donne une apparence plus ronde. Cependant, le cœur de ce Pokémon reste dur, rocailleux et rugueux.', 'Jet Pierre, Charge', 'Eboulement, Tombe roche, tunnel', 'Combat, Sol, Acier, Eau, Plante, Glace', 'Normal, Vol, Poison, Roche, Feu, Electrik', 'Aucune', 'img/pokemon/74.png', 'img/card/74.png'),
(75, 'Gravalanch', 'Roche,  Sol', 'Gravalanch grandit en se nourrissant de cailloux. Apparemment, il a une préférence pour les cailloux recouverts de mousse. En moyenne, il mange une tonne de rochers par jour.', 'Jet Pierre, Coupdboue', 'Lame de roc, Boule de roc, Tunnel', 'Combat, Sol, Acier, Eau, Plante, Glace', 'Normal, Vol, Poison, Roche, Feu, Electrik', 'Aucune', 'img/pokemon/75.png', 'img/card/75.png'),
(76, 'Grolem', 'Roche,  Sol', 'Grolem vit à la montagne. Lorsquil y a un tremblement de terre, ces Pokémon roulent en groupe vers les contreforts montagneux.', 'Jet Pierre, Coupdboue', 'Lame de roc, Boule de roc, Seisme', 'Combat, Sol, Acier, Eau, Plante, Glace', 'Normal, Vol, Poison, Roche, Feu, Electrik', 'Aucune', 'img/pokemon/76.png', 'img/card/76.png'),
(77, 'Ponyta', 'Feu', 'À sa naissance, Ponyta est très faible. Il peut à peine tenir debout. Ce Pokémon se muscle en trébuchant et en tombant, lorsquil essaie de suivre ses parents.', 'Charge, Flammèche', 'Nitro charge, Roue de feu, Ecrasement', 'Sol, roche, eau', 'Insecte, acier, feu, plante, glace, feu', 'Aucune', 'img/pokemon/77.png', 'img/card/77.png'),
(78, 'Galopa', 'Feu', 'On voit souvent Galopa trotter dans les champs et les plaines. Cependant, lorsque ce Pokémon sen donne la peine, il peut galoper à plus de 240 km, h et sa crinière flamboyante sembrase.', 'Balayage, Danse Flamme', 'Déflagration, Tunneller, Canicule', 'Sol, roche, eau', 'Insecte, acier, feu, plante, glace, feu', 'Aucune', 'img/pokemon/78.png', 'img/card/78.png'),
(79, 'Ramoloss', 'Eau,  Psy', 'Ramoloss trempe sa queue dans leau au bord des rivières pour attraper ses proies. Cependant, ce Pokémon oublie souvent ce quil fait là et passe des jours entiers à traîner au bord de leau.', 'Pistolet à O, Choc Mental ', 'Vibraqua, Choc psy, Psyko', 'Insecte, specte, Plante, Electrick, Ténèbre', 'Combat, Acier, Feu, Eau, Psy, Glace', 'Aucune', 'img/pokemon/79.png', 'img/card/79.png'),
(80, 'Flagadoss', 'Eau,  Psy', 'Flagadoss a un Kokiyas solidement attaché à sa queue. Du coup, il ne peut plus lutiliser pour pêcher. Flagadoss est donc obligé, à contrecœur, de nager pour attraper ses proies.', 'Pistolet à O, Choc Mental ', 'Vibraqua, Laser glace, Psyko', 'Insecte, specte, Plante, Electrick, Ténèbre', 'Combat, Acier, Feu, Eau, Psy, Glace', 'Aucune', 'img/pokemon/80.png', 'img/card/80.png'),
(81, 'Magnéti', 'Electrick,  Acier', 'Magnéti sattache aux lignes à haute tension pour se charger en électricité. Si une maison a une panne de courant, il est conseillé de vérifier les fusibles car on trouve parfois ces Pokémon amassés sur la boîte à fusibles.', 'Etincelle, Eclair', 'Coup djus, Bombaimant, Tonnerre', 'Sol, Combat, Feu', 'Normal, Vol, Poison, Roche; Insecte, Acier, Plante, Electrick, Psy, Glace, Dragon, Fée ', 'Aucune', 'img/pokemon/81.png', 'img/card/81.png'),
(82, 'Magnéton', 'Electrick,  Acier', 'Magnéton émet un puissant champ magnétique qui neutralise les appareils mécaniques. Lorsque ces Pokémon débarquent en masse, les villes sonnent lalarme et préviennent les habitants.', 'Etincelle, Rayon chargé', 'Elécanon, Bombaimant, Luminocanon', 'Sol, Combat, Feu', 'Normal, Vol, Poison, Roche; Insecte, Acier, Plante, Electrick, Psy, Glace, Dragon, Fée ', 'Aucune', 'img/pokemon/82.png', 'img/card/82.png'),
(83, 'Canarticho', 'Normal, Vol', 'On voit souvent des Canarticho avec une tige, récupérée sur une plante quelconque. Apparemment, ils peuvent distinguer les bonnes des mauvaises. On a vu ces Pokémon se battre pour des histoires de tiges.', 'Taillade, Lame dair', 'Aéropique, Tranchair, Lame Feuille', 'Roche, Electick, Glace', 'Insecte, Spectre, Plante', 'Sol', 'img/pokemon/83.png', 'img/card/83.png'),
(84, 'Doduo', 'Normal, Vol', 'Les deux têtes de Doduo ne dorment jamais en même temps. Elles se reposent à tour de rôle pour que lune puisse monter la garde pendant que lautre dort.', 'Pic-Pic, Vive attaque', 'Bec vrille, Aéropique, Rapace', 'Electrick, Roche, Glace', 'Insecte, Plante', 'Sol, Spectre', 'img/pokemon/84.png', 'img/card/84.png'),
(85, 'Dodrio', 'Normal, Vol', 'Il faut se méfier lorsque les trois têtes de Dodrio regardent dans des directions différentes. Cela signifie quil est sur ses gardes. Si cest le cas, il vaut mieux ne pas sapprocher de ce Pokémon, il pourrait décider dattaquer.', 'Feinte, Aile dacier', 'Bec vrille, Aéropique, Rapace', 'Electrick, Roche, Glace', 'Insecte, Plante', 'Sol, Spectre', 'img/pokemon/85.png', 'img/card/85.png'),
(86, 'Otaria', 'Eau', 'Otaria chasse ses proies dans leau gelée, sous la couche de glace. Lorsquil cherche à respirer, il perce un trou en frappant la glace avec la partie saillante de sa tête.', 'Eclats glace, Léchouilles', 'Vent glace, Hydroqueue, Onde Boréale ', 'Plante, Electrick', 'Acier, Feu, Eau, Glace', 'Aucune', 'img/pokemon/86.png', 'img/card/86.png'),
(87, 'Lamantine', 'Eau,  Glace', 'Lamantine adore piquer un roupillon à même la glace. Il y a très longtemps, un marin ayant aperçu ce Pokémon dormant sur un glacier a cru voir une sirène.', 'Souffle glacé, Queue de fer', 'Blizzard, Vibraqua, Onde Boréale', 'Combat, Roche, Plante, Electrick', 'Eau, Glace', 'Aucune', 'img/pokemon/87.png', 'img/card/87.png'),
(88, 'Tadmory', 'Poison', 'Le corps boueux et gélatineux de Tadmorv peut senfoncer dans nimporte quelle ouverture, même la plus petite. Ce Pokémon se promène dans les tuyaux des égouts pour boire de leau croupie.', 'Coup dboue, Direct Toxic', 'Detritus, Boue-Bombe, Bomb-Beurk', 'Sol, Psy', 'Combat, Poison, Insecte, Plante, Fée', 'Aucune', 'img/pokemon/88.png', 'img/card/88.png'),
(89, 'Grotadmorv', 'Poison', 'Un fluide nauséabond suinte du corps de Grotadmorv, agressant les narines de ses ennemis. Une seule goutte de ce fluide suffit à faire croupir un bassin deau propre.', 'Harcèlement, Direct Toxic', 'Vibroscur, Detritus, Cradovague', 'Sol, Psy', 'Combat, Poison, Insecte, Plante, Fée', 'Aucune', 'img/pokemon/89.png', 'img/card/89.png'),
(90, 'Kokiyas', 'Eau', 'La nuit, ce Pokémon utilise sa grande langue pour creuser un trou dans le sable des fonds marins afin dy dormir. Une fois endormi, Kokiyas referme sa coquille, mais laisse sa langue dépasser.', 'Eclats glace, Charge', 'Bulle dO, Vibraqua, Vent glace', 'Plante, Electrick', 'Acier, Feu, Eau, Glace', 'Aucune', 'img/pokemon/90.png', 'img/card/90.png'),
(91, 'Crustabri', 'Eau, Glace', 'Crustabri est capable de se déplacer dans les fonds marins en avalant de leau et en la rejetant vers larrière. Ce Pokémon envoie des pointes en utilisant la même méthode', 'Souffle glacé, Eclats glace', 'Hydrocanon, Onde boréale, Avalanche, Vent glace, Blizzard', 'Combat, Roche, Electrick, Plante', 'Eau, Glace', 'Aucune', 'img/pokemon/91.png', 'img/card/91.png'),
(92, 'Fantominus', 'Spectre, Poison', 'Fantominus est principalement constitué de matière gazeuse. Lorsquil est exposé au vent, son corps gazeux se disperse et diminue. Des groupes de ce Pokémon se rassemblent sous les auvents des maisons pour se protéger.', 'Léchouille, Etonnement', 'Vibroscur, Bomb-Beurk, Ombre Nocturne', 'Sol, Spectre, Psy, Ténèbres', 'Poison, Insecte, Plante, Fée', 'Normal, Combat', 'img/pokemon/92.png', 'img/card/92.png'),
(93, 'Spectrum', 'Spectre, Poison', 'Spectrum est un Pokémon dangereux. Si lun dentre eux fait signe dapprocher, il ne faut jamais lécouter. Ce Pokémon risque de sortir sa langue pour essayer de voler votre vie.', 'Griffe ombre, Etonnement', 'Vibroscur, Bomb-Beurk, Point hombre', 'Sol, Spectre, Psy, Ténèbres', 'Poison, Insecte, Plante, Fée', 'Normal, Combat', 'img/pokemon/93.png', 'img/card/93.png'),
(94, 'Ectoplasma', 'Spectre, Poison', 'Parfois, pendant les nuits noires, une ombre projetée par un réverbère peut tout à coup vous dépasser. Il sagit dun Ectoplasma qui court, en se faisant passer pour lombre de quelquun dautre.', 'Coup bas, Chatiment', 'Ballombre, Bomb-Beurk, Exploforce', 'Sol, Spectre, Psy, Ténèbres', 'Poison, Insecte, Plante, Fée', 'Normal, Combat', 'img/pokemon/94.png', 'img/card/94.png'),
(95, 'Onix', 'Roche,  Sol', 'Onix a dans le cerveau un aimant qui lui sert de boussole. Il permet à ce Pokémon de ne pas se perdre pendant quil creuse. En prenant de lâge, son corps sarrondit et se polit', 'Jet Pierre, Charge', 'Lame de roc, Tourbi Sable, Tacle lourd, Eboulement, Tete de fer', 'Eau, Plante, Sol, Glace, Acier, Combat', 'Normal, Roche, Vol, Feu, Electrick, Poison', 'Aucune', 'img/pokemon/95.png', 'img/card/95.png'),
(96, 'Soporifik', 'Psy', 'Lorsque les enfants ont le nez qui les démange en dormant, cest sans doute parce que ce Pokémon se tient au-dessus de leur oreiller, afin dessayer de manger leurs rêves par leurs narines.', 'Ecras face, Choc Mental', 'Rafale Psy, Choc Psy, Psyko', 'Insecte, Spectre, Ténèbres', 'Combat, Psy', 'Aucune', 'img/pokemon/96.png', 'img/card/96.png'),
(97, 'Hypnomade', 'Psy', 'Hypnomade tient un pendule dans sa main. Le mouvement de balancier et les reflets brillants du pendule hypnotisent profondément son ennemi. Lorsque ce Pokémon cherche ses proies, il nettoie son pendule.', 'Psykoud’Boul, Choc Mental', 'Prescience, Exploforce, Psyko', 'Insecte, Spectre, Ténèbres', 'Combat, Psy', 'Aucune', 'img/pokemon/97.png', 'img/card/97.png'),
(98, 'Krabby', 'Eau', 'Krabby vit sur les plages, enterré dans le sable. Sur les plages où on trouve peu de nourriture, on peut voir ces Pokémon se disputer pour défendre leur territoire.', 'Ecume, tir de boue', 'Force Poigne, Bulle dO, Vibraqua', 'Plante, Electick', 'Acier, Eau, Feu, Glace', 'Aucune', 'img/pokemon/98.png', 'img/card/98.png'),
(99, 'Kraboss', 'Eau', 'Krabboss est doté dune pince gigantesque, surdimensionnée. Il lagite en lair pour communiquer avec ses semblables. En revanche, sa pince est tellement lourde que ce Pokémon se fatigue très vite.', 'Ecume, Griffe dacier', 'Force Poigne, Plaie Croix, Vibraqua', 'Plante, Electick', 'Acier, Eau, Feu, Glace', 'Aucune', 'img/pokemon/99.png', 'img/card/99.png'),
(100, 'Voltorbe', 'Electrick', 'La première fois quon a vu Voltorbe, cétait dans une usine qui fabrique des Poké Balls. Personne na jamais pu expliquer le lien entre cet événement et la ressemblance frappante de ce Pokémon avec une Poké Ball.', 'Etincelle, Charge', 'Coup djus, Tonnerre, Gyroballe', 'Sol', 'Vol, Acier, Électrik', 'Aucune', 'img/pokemon/100.png', 'img/card/100.png'),
(101, 'Électrode', 'Électrik', 'Électrode mange lélectricité qui se trouve dans latmosphère. Les jours dorage, on peut voir ce Pokémon exploser sans arrêt parce quil a avalé trop délectricité', 'Étincelle, Change Eclair, Charge', 'Coup dJus, Tonnere, Ultralaser', 'Sol', 'Acier, Électrik, Vol', 'Aucune', 'img/pokemon/101.png', 'img/card/101.png'),
(102, 'Noeunoeuf', 'Plante, Psy', 'Ce Pokémon est constitué de six œufs formant une grappe serrée. Ces six œufs sattirent mutuellement et pivotent. Quand des fissures apparaissent sur les coquilles, ça signifie que Noeunoeuf est sur le point dévoluer.', 'Choc Mental, Balle Graine', 'Canon Graine, Psyko, Pouvoir Antique', 'Insecte, Feu, Glace, Vol, Poison, Ténebres, Spectre', 'Combat, Eau, Plante, Électrik, Psy, Sol', 'Aucune', 'img/pokemon/102.png', 'img/card/102.png'),
(103, 'Noadkoko', 'Plante, Psy', 'Noadkoko vient des tropiques. À force de vivre sous un soleil ardent, ses têtes ont rapidement grandi. On raconte que lorsque ses têtes tombent, elles se rassemblent et forment un Noeunoeuf', 'Extrasenseur, Balle Graine', 'Canon Graine, Psyko, Lance-Soleil', 'Insecte, Feu, Glace, Vol, Poison, Ténebres, Spectre', 'Combat, Eau, Plante, Électrik, Psy, Sol', 'Aucune', 'img/pokemon/103.png', 'img/card/103.png'),
(104, 'Osselait', 'Sol', 'La maman dOsselait lui manque terriblement et il ne la reverra jamais. La lune le fait pleurer, car elle lui rappelle sa mère. Les taches sur le crâne que porte ce Pokémon sont les marques de ses larmes.', 'Coud’Boue, Éclate-Roc', 'Massd’Os, Tunnel, Piétisol', 'Eau, Plante, Glace', 'Poison, Roche, Électrik', 'Aucune', 'img/pokemon/104.png', 'img/card/104.png'),
(105, 'Ossatueur', 'Sol', 'Ossatueur est la forme évoluée dOsselait. Il a surmonté le chagrin causé par la perte de sa maman et sest endurci. Le tempérament décidé et entier de ce Pokémon le rend très difficile à amadouer.', 'Coud’Boue, Éclate-Roc', 'Massd’Os, Tunnel, Séisme', 'Eau, Plante, Glace', 'Poison, Roche, Électrik', 'Aucune', 'img/pokemon/105.png', 'img/card/105.png'),
(106, 'Kicklee', 'Combat', 'Les jambes de Kicklee peuvent se contracter et sétirer à volonté. Grâce à ces jambes à ressort, il terrasse ses ennemis en les rouant de coups de pied. Après les combats, il masse ses jambes pour éviter de sentir la fatigue.', 'Balayage, Éclate-Roc', 'Balayette, Lame de Roc, Close Combat', 'Fée, Psy, Vol', 'Roche, Insecte, Ténèbres', 'Aucune', 'img/pokemon/106.png', 'img/card/106.png'),
(107, 'Tygnon', 'Combat', 'On raconte que Tygnon dispose de létat desprit dun boxeur qui sentraîne pour le championnat du monde. Ce Pokémon est doté dune ténacité à toute épreuve et nabandonne jamais face à ladversité.', 'Pisto-Poing, Riposte, Éclate-Roc', 'Poing de Feu, Poing-Glace, Poing-Éclair, Close Combat, Casse Brique ', 'Fée, Psy, Vol', 'Roche, Insecte, Ténèbres', 'Aucune', 'img/pokemon/107.png', 'img/card/107.png'),
(108, 'Excelangue', 'Normal', 'Chaque fois quExcelangue découvre quelque chose de nouveau, il le lèche. Sa mémoire est basée sur le goût et la texture des objets. Il naime pas les choses acides.', 'Léchouille, Psykoud’Boul', 'Ultralaser, Écrasement, Mégafouet', 'Combat', 'Aucune', 'Spectre', 'img/pokemon/108.png', 'img/card/108.png'),
(109, 'Smogo', 'Poison', 'Lorsque Smogo sagite, ça augmente la toxicité de ses gaz internes. Il les projette ensuite par les nombreux orifices de son corps. Ce Pokémon peut aussi gonfler son corps et le faire exploser', 'Charge, Harcèlement', 'Détritus, Bomb-Beurk, Vibrobscur', 'Sol, Psy', 'Combat, Poison, Insecte, Plante, Fée', 'Aucune', 'img/pokemon/109.png', 'img/card/109.png'),
(110, 'Smogogo', 'Poison', 'Smogogo adore les gaz qui se dégagent des aliments pourris dans les poubelles. Ce Pokémon cherche généralement les maisons sales et mal tenues pour y habiter. La nuit, quand tout le monde est endormi, il fouille les détritus', 'Charge, Harcèlement', 'Ball’Ombre, Bomb-Beurk, Vibrobscur', 'Sol, Psy', 'Combat, Poison, Insecte, Plante, Fée', 'Aucune', 'img/pokemon/110.png', 'img/card/110.png'),
(111, 'Rhinocorne', 'Sol, Roche', 'Rhinocorne charge droit devant lui, détruisant tout sur son passage. Il ne sarrête jamais, même lorsquil charge un bloc dacier. Malgré tout, il sent la douleur le lendemain', 'Coud’Boue, Éclate-Roc', 'Piétisol, Koud’Korne, Écrasement', 'Combat, Sol, Acier, Eau, Plante, Glace', 'Normal, Vol, Poison, Roche, Feu, Électrik', 'Aucune', 'img/pokemon/111.png', 'img/card/111.png'),
(112, 'Rhinoferos', 'Sol, Roche', 'La corne de Rhinoféros peut même casser du diamant brut. Et avec un simple coup de queue, il peut détruire un bâtiment. La peau de ce Pokémon est incroyablement dure. Un boulet de canon ne lui ferait même pas une égratignure.', 'Coud’Boue, Éclate-Roc', 'Mégacorne, Séisme, Lame de Roc', 'Combat, Sol, Acier, Eau, Plante, Glace', 'Normal, Vol, Poison, Roche, Feu, Électrik', 'Aucune', 'img/pokemon/112.png', 'img/card/112.png'),
(113, 'Leveinard', 'Normal', 'Leveinard pond tous les jours des œufs pleins de vitamines. Ces œufs sont tellement bons que les gens les mangent même quand ils nont pas faim.', 'Écras’Face, Psykoud’Boul', 'Psyko, Éclat Magique, Ultralaser', 'Combat', 'Spectre', 'Aucune', 'img/pokemon/113.png', 'img/card/113.png'),
(114, 'Saquedeneu', 'Plante', 'Les lianes de Saquedeneu se brisent facilement lorsquon les attrape. Cela ne lui fait pas mal et lui permet simplement de séchapper rapidement. Les lianes cassées repoussent le lendemain.', 'Vol, Poison, Insecte, Feu, Glace', 'Sol, Eau, Plante, Électrik', 'Fouet Lianes, Harcèlement', 'Bomb-Beurk, Lance-Soleil, Nœud Herbe', 'Aucune', 'img/pokemon/114.png', 'img/card/114.png'),
(115, 'Kangourex', 'Normal', 'Lorsquon rencontre un petit Kangourex qui joue tout seul, il ne faut jamais le déranger ou essayer de lattraper. Les parents du bébé Pokémon sont sûrement dans le coin et ils risquent dentrer dans une colère noire.', 'Coud’Boue, Balayage', 'Séisme, Colère, Mâchouille', 'Combat', 'Aucune', 'Spectre', 'img/pokemon/115.png', 'img/card/115.png'),
(116, 'Hypotrempe', 'Eau', 'Hypotrempe mange des petits insectes et de la mousse trouvée sur les cailloux. Lorsque les courants océaniques sont trop forts, ce Pokémon peut sancrer en accrochant sa queue aux rochers ou aux coraux.', 'Pistolet à 0, Écume', 'Bulles d’O, Dracochoc, Luminocanon', 'Plante, Électrik', 'Acier, Feu, Eau, Glace', 'Aucune', 'img/pokemon/116.png', 'img/card/116.png'),
(117, 'Hypocean', 'Eau', 'Hypocéan saccroche aux récifs de corail avant de sendormir. Les pêcheurs de coraux se font parfois piquer par les aiguillons de ce Pokémon lorsquils ne font pas attention', 'Pistolet à O, Dracosouffle', 'Hydrocanon, Dracochoc, Onde Boréale', 'Plante, Électrik', 'Acier, Feu, Eau, Glace', 'Aucune', 'img/pokemon/117.png', 'img/card/117.png'),
(118, 'Poissirène', 'Eau', 'Poissirène est un Pokémon magnifique doté de nageoires qui ondulent élégamment dans les profondeurs. Il ne faut pourtant pas baisser sa garde face à ce Pokémon, car il peut charger avec sa puissante corne', 'Picpic, Tir de Boue', 'Vibraqua, Koud’Korne, Hydroqueue', 'Plante, Électrik', 'Acier, Feu, Eau, Glace', 'Aucune', 'img/pokemon/118.png', 'img/card/118.png'),
(119, 'Poissoroy', 'Eau', 'En automne, on peut voir les Poissoroy mâles effectuer des danses nuptiales dans les rivières pour plaire aux femelles. Cest pendant cette saison que le corps de ce Pokémon prend ses plus belles couleurs.', 'Picpic, Direct Toxik', 'Mégacorne, Laser Glace, Vibraqua', 'Plante, Électrik', 'Acier, Feu, Eau, Glace', 'Aucune', 'img/pokemon/119.png', 'img/card/119.png'),
(120, 'Stari', 'Eau', 'Au centre de Stari se trouve un organe rouge et brillant appelé le cœur. À la fin de lété, sur les plages, les cœurs de ces Pokémon brillent comme les étoiles dans le ciel', 'Pistolet à O, Charge', 'Météores, Bulles d’O, Rayon Gemme', 'Plante, Électrik', 'Acier, Feu, Eau, Glace', 'Aucune', 'img/pokemon/120.png', 'img/card/120.png'),
(121, 'Staross', 'Eau, Psy', 'Le centre de Staross, son cœur, resplendit de sept différentes couleurs. Du fait de sa brillance naturelle, on appelle ce Pokémon le « joyau des mers ».', 'Pistolet à O, Puissance Cachée', 'Hydrocanon, Psyko, Rayon Gemme', 'Plante, Électrik, Insecte, Spectre, Ténèbres', 'Acier, Combat, Feu, Eau, Psy, Glace', 'Aucune', 'img/pokemon/121.png', 'img/card/121.png'),
(122, 'M. Mime', 'Psy, Fée', 'M. Mime est un pantomime hors pair. Ses gestes et ses mouvements parviennent à faire croire que quelque chose dinvisible existe réellement. Lorsquon y croit, ces choses deviennent palpables.', 'Choc Mental, Psykoud’Boul', 'Rafale Psy, Psyko, Ball’Ombre', 'Combat, Psy', 'Dragon', 'Aucune', 'img/pokemon/122.png', 'img/card/122.png'),
(123, 'Insécateur', 'Insecte, Vol', 'Insécateur est incroyablement rapide. Sa vitesse fulgurante améliore lefficacité des deux lames situées sur ses avant-bras. Elles sont si coupantes quelles peuvent trancher un énorme tronc darbre en un coup.', 'Taillade, Lame d’Air', 'Tranche-Nuit, Plaie-Croix, Aéropique', 'Vol, Roche, Feu, Électrik, Glace', 'Combat, Sol, Insecte, Plante\r\n', 'Aucune', 'img/pokemon/123.png', 'img/card/123.png'),
(124, 'Lippoutou', 'Glace, Psy', 'Lippoutou marche en rythme, ondule de tout son corps et se déhanche comme sil dansait. Ses mouvements sont si communicatifs que les gens qui le voient sont soudain pris dune terrible envie de bouger les hanches, sans réfléchir.', 'Souffle Glacé, Choc Mental', 'Vampibaiser, Avalanche, Choc Psy', 'Insecte, Roche, Feu, Spectre, Acier, Ténèbres', 'Psy, Glace', 'Aucune', 'img/pokemon/124.png', 'img/card/124.png'),
(125, 'Elektek', 'Électrik', 'Lorsquune tempête approche, des groupes entiers de ce Pokémon se battent pour grimper sur les hauteurs, où la foudre a le plus de chance de tomber. Certaines villes se servent dÉlektek en guise de paratonnerres.', 'Éclair, Balayage', 'Poing-Éclair, Tonnerre, Fatal-Foudre', 'Sol', 'Vol, Acier, Électrik', 'Aucune', 'img/pokemon/125.png', 'img/card/125.png'),
(126, 'Magmar', 'Feu', 'Lorsquil se bat, Magmar fait jaillir des flammes de son corps pour intimider son adversaire. Les explosions enflammées de ce Pokémon déclenchent des vagues de chaleur qui embrasent la végétation environnante.', 'Flammèche, Poing-Karaté', 'Déflagration, Poing de Feu, Lance-Flammes', 'Sol, Roche, Eau', 'Insecte, Acier, Feu, Plante, Glace, Fée', 'Aucune', 'img/pokemon/126.png', 'img/card/126.png'),
(127, 'Scarabrute', 'Insecte', ' Scarabrute est incroyablement fort. Il peut attraper un ennemi qui pèse deux fois son poids dans ses mandibules et le soulever sans le moindre problème. Lorsquil fait froid, les mouvements de ce Pokémon sont un peu ralentis.', 'Éclate-Roc, Piqûre', 'Force Poigne, Plaie-Croix, Close Combat', 'Vol, Roche, Feu', 'Combat, Sol, Plante', 'Aucune', 'img/pokemon/127.png', 'img/card/127.png'),
(128, 'Tauros', 'Normal', 'Ce Pokémon nest pas satisfait sil ne détruit pas tout sur son passage. Lorsque Tauros ne trouve pas dadversaire, il se rue sur de gros arbres et les déracine pour passer ses nerfs.', 'Charge, Psykoud’Boul', 'Koud’Korne, Tête de Fer, Séisme', 'Combat', 'Aucune', 'Spectre', 'img/pokemon/128.png', 'img/card/128.png'),
(129, 'Magicarpe', 'Eau', 'Magicarpe est un Pokémon ridicule qui ne sait faire que des ronds dans leau ou se laisser porter par les courants. Son comportement a donné envie aux savants détudier son cas.', 'Trempette', 'Lutte', 'Plante, Électrik', 'Acier, Feu, Eau, Glace', 'Aucune', 'img/pokemon/129.png', 'img/card/129.png');
INSERT INTO `pokemon` (`id`, `nom`, `type`, `description`, `attaque_rapide`, `attaque_special`, `faiblesse`, `resistance`, `immunite`, `link_img`, `link_card`) VALUES
(130, 'Léviator', 'Eau', 'Quand Magicarpe évolue et devient Léviator, la structure de ses cellules cérébrales est modifiée. On pense que lextrême violence de ce Pokémon découle de cette modification.', 'Morsure, Draco-Queue', 'Hydrocanon, Colère, Mâchouille', 'Plante, Électrik', 'Acier, Feu, Eau, Glace', 'Aucune', 'img/pokemon/130.png', 'img/card/130.png'),
(131, 'Lokhlass', 'Eau, Glace', 'Les Lokhlass sont en voie dextinction. Le soir, on entend ce Pokémon chantonner une complainte mélancolique, espérant retrouver ses rares congénères.', 'Souffle Glacé, Pistolet à 0, Éclats Glace', 'Blizzard, Hydrocanon, Surf, Dracochoc, Laser Glace', 'Combat, Roche, Plante, Électrik', 'Eau, Glace', 'Aucune', 'img/pokemon/131.png', 'img/card/131.png'),
(132, 'Métamorph', 'Normal', 'Métamorph peut modifier sa structure moléculaire pour prendre dautres formes. Lorsquil essaie de se transformer de mémoire, il lui arrive de se tromper sur certains détails.', 'Morphing', 'Lutte', 'Combat', 'Spectre', 'Aucune', 'img/pokemon/132.png', 'img/card/132.png'),
(133, 'Évoli', 'Normal', 'Évoli a une structure génétique instable qui se transforme en fonction de lenvironnement dans lequel il vit. Ce Pokémon peut évoluer grâce aux radiations de diverses pierres.', 'Vive-Attaque, Charge', 'Tunnel, Météores', 'Combat', 'Spectre', 'Aucune', 'img/pokemon/133.png', 'img/card/133.png'),
(134, 'Aquali', 'Eau', 'Aquali a subi une mutation spontanée. Des nageoires et des branchies sont apparues sur son corps, ce qui lui permet de vivre dans les fonds marins. Ce Pokémon peut contrôler leau à volonté.', 'Pistolet à 0', 'Vibraqua, Hydrocanon, Hydroqueue', 'Plante, Électrik', 'Acier, Feu, Eau, Glace', 'Aucune', 'img/pokemon/134.png', 'img/card/134.png'),
(135, 'Voltali', 'Électrik', 'Les cellules de Voltali génèrent un courant de faible intensité. Ce pouvoir est amplifié par lélectricité statique de ses poils, ce qui lui permet denvoyer des éclairs. Sa fourrure hérissée est faite daiguilles chargées délectricité.', 'Éclair, Change Éclair', 'Coup d’Jus, Tonnerre, Fatal-Foudre', 'Sol', 'Acier, Vol, Électrik', 'Aucune', 'img/pokemon/135.png', 'img/card/135.png'),
(136, 'Pyroli', 'Feu', 'La fourrure soyeuse de Pyroli a une fonction anatomique. Elle rejette la chaleur dans lair pour que son corps ne surchauffe pas. La température du corps de ce Pokémon peut atteindre 900 °C.', 'Flammèche, Danse Flamme', 'Déflagration, Lance-Flammes, Surchauffe', 'Sol, Roche, Eau', 'Insecte, Acier, Feu, Plante, Glace, Fée', 'Aucune', 'img/pokemon/136.png', 'img/card/136.png'),
(137, 'Porygon', 'Normal', 'Porygon est capable de se décompiler et de retourner à létat de programme informatique pour entrer dans le cyberespace. Ce Pokémon est protégé contre le piratage, il est donc impossible de le copier.', 'Rayon Chargé, Puissance Cachée', 'Ultralaser, Lance-Soleil, Élecanon', 'Combat', 'Spectre', 'Aucune', 'img/pokemon/137.png', 'img/card/137.png'),
(138, 'Amonita', 'Roche, Eau', 'Amonita est lun des Pokémon disparus depuis longtemps et qui furent ressuscités à partir de fossiles. Lorsquil est attaqué par un ennemi, il se rétracte dans sa coquille.', 'Pistolet à O, Tir de Boue', 'Pouvoir Antique, Bulles d’O, Boule Roc', 'Combat, Sol, Plante, Électrik', 'Normal, Vol, Poison, Feu, Glace', 'Aucune', 'img/pokemon/138.png', 'img/card/138.png'),
(139, 'Amonistar', 'Roche, Eau', 'En plus de pouvoir le rencontrer au hasard dune promenade, Amonistar est disponible en faisant évoluer Amonita pour 50 bonbons.', 'Pistolet à O, Tir de Boue', 'Pouvoir Antique, Bulles d’O, Boule Roc', 'Combat, Sol, Plante, Électrik', 'Normal, Vol, Poison, Feu, Glace', 'Aucune', 'img/pokemon/139.png', 'img/card/139.png'),
(140, 'Kabuto', 'Roche, Eau', 'Kabuto est un Pokémon ressuscité à partir dun fossile. Cependant, on a découvert des spécimens vivants. Ce Pokémon na pas changé depuis 300 millions dannées.', 'Griffe, Tir de Boue', 'Pouvoir Antique, Aqua-Jet, Tomberoche', 'Combat, Sol, Plante, Électrik', 'Normal, Vol, Poison, Feu, Glace', 'Aucune', 'img/pokemon/140.png', 'img/card/140.png'),
(141, 'Kabutops', 'Roche, Eau', 'Jadis, Kabutops plongeait dans les profondeurs pour trouver ses proies. Apparemment, ce Pokémon vivant sur terre est lévolution dune créature marine, comme le prouvent les changements dans ses branchies.', 'Tir de Boue, Éclate Roc, Taillade', 'Pouvoir Antique, Vibraqua, Lame de Roc', 'Combat, Sol, Plante, Électrik', 'Normal, Vol, Poison, Feu, Glace', 'Aucune', 'img/pokemon/141.png', 'img/card/141.png'),
(142, 'Ptéra', 'Roche, Vol', 'Ptéra est un Pokémon de lère des dinosaures. Il fut ressuscité à partir de cellules extraites dun morceau dambre. On pense quil était le roi des cieux à lépoque préhistorique.', 'Aile d’Acier, Morsure', 'Pouvoir Antique, Tête de Fer, Ultralaser', 'Roche, Acier, Eau, Électrik, Glace', 'Normal, Vol, Poison, Insecte, Feu', 'Aucune', 'img/pokemon/142.png', 'img/card/142.png'),
(143, 'Ronflex', 'Normal', 'Les journées de Ronflex se résument aux repas et aux siestes. Cest un Pokémon tellement gentil que les enfants nhésitent pas à jouer sur son énorme ventre.', 'Psykoud’Boul, Léchouille', 'Ultralaser, Séisme, Tacle Lourd', 'Combat', 'Spectre', 'Aucune', 'img/pokemon/143.png', 'img/card/143.png'),
(144, 'Artikodin', 'Glace, Vol', 'Artikodin est un Pokémon Oiseau légendaire qui peut contrôler la glace. Le battement de ses ailes gèle lair tout autour de lui. Cest pourquoi on dit que lorsque ce Pokémon vole, il va neiger.', 'Souffle Glacé', 'Laser Glace, Vent Glace, Blizzard', 'Roche, Acier, Feu, Électrik', 'Plante, Insecte, Sol', 'Aucune', 'img/pokemon/144.png', 'img/card/144.png'),
(145, 'Électhor', 'Vol, Électrik', 'Électhor est un Pokémon Oiseau légendaire capable de contrôler lélectricité. Il vit généralement dans les nuages orageux. Ce Pokémon gagne en puissance lorsquil est frappé par la foudre.', 'Rayon Chargé', 'Tonnerre, Fatal-Foudre, Élecanon', 'Roche, Glace', '\r\nRoche, Glace, Combat, Vol, Insecte, Plante, Acier', 'Aucune', 'img/pokemon/145.png', 'img/card/145.png'),
(146, 'Sulfura', 'Vol, Feu', 'Sulfura est un Pokémon Oiseau légendaire capable de contrôler le feu. On raconte que lorsque ce Pokémon est blessé, il se baigne dans le magma en ébullition dun volcan pour se soigner.', 'Danse Flamme', 'Déflagration, Canicule, Surchauffe', 'Roche, Eau, Électrik', 'Combat, Feu, Fée, Insecte, Plante, Acier', '', 'img/pokemon/146.png', 'img/card/146.png'),
(147, 'Minidraco', 'Dragon', 'Minidraco mue constamment, renouvelant sans arrêt sa peau. En effet, lénergie vitale de son corps augmente régulièrement et sa mue lui permet déviter datteindre des niveaux incontrôlables.', 'Dracosouffle, Queue de Fer', 'Ligotage, Ouragan, Hydroqueue', 'Glace, Dragon, Fée', 'Feu, Eau, Plante, Électrik', 'Aucune', 'img/pokemon/147.png', 'img/card/147.png'),
(148, 'Draco', 'Dragon', 'Draco stocke une quantité dénergie considérable dans son corps. On raconte quil peut modifier les conditions climatiques autour de lui en déchargeant lénergie contenue dans les cristaux de son cou et de sa queue.', 'Dracosouffle, Queue de Fer', 'Ligotage, Ouragan, Hydroqueue', 'Glace, Dragon, Fée', 'Feu, Eau, Plante, Électrik', 'Aucune', 'img/pokemon/148.png', 'img/card/148.png'),
(149, 'Dracolosse', 'Dragon, Vol', 'Dracolosse est capable de faire le tour de la planète en seize heures à peine. Cest un Pokémon au grand cœur qui ramène à bon port les navires perdus dans les tempêtes', 'Draco-Queue, Aile d’Acier', 'Ultralaser, Vent Violent, Colère', 'Glace, Dragon, Fée, Roche', 'Feu, Eau, Plante, Sol, Combat, Insecte', 'Aucune', 'img/pokemon/149.png', 'img/card/149.png'),
(150, 'Mewtwo', 'Psy', 'Mewtwo est un Pokémon créé par manipulation génétique. Cependant, bien que les connaissances scientifiques des humains aient réussi à créer son corps, elles nont pas pu doter Mewtwo dun cœur sensible.', 'Coupe Psycho', 'Psyko, Ball’Ombre, Ultralaser, Exploforce', 'Insecte, Spectre, Ténèbres', 'Combat, Psy', 'Aucune', 'img/pokemon/150.png', 'img/card/150.png'),
(151, 'Mew', 'Psy', 'On dit que Mew possède le code génétique de tous les autres Pokémon. Il peut se rendre invisible à sa guise, ce qui lui permet de ne pas se faire remarquer quand il sapproche des gens.', 'Écras’Face', 'Séisme, Psyko, Fatal-Foudre, Déflagration, Lance-Soleil, Ultralaser, Blizzard, Exploforce', 'Insecte, Spectre, Ténèbres', 'Combat, Psy', 'Aucune', 'img/pokemon/151.png', 'img/card/151.png');

-- --------------------------------------------------------

--
-- Structure de la table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nom` text NOT NULL,
  `prenom` text NOT NULL,
  `mail` text NOT NULL,
  `pseudo` text NOT NULL,
  `password` text NOT NULL,
  `naissance` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=57 DEFAULT CHARSET=latin1;

--
-- Déchargement des données de la table `users`
--

INSERT INTO `users` (`id`, `nom`, `prenom`, `mail`, `pseudo`, `password`, `naissance`) VALUES
(2, 'Bass', 'Louise', 'Louise.Bass@hotmail.fr', 'Louisebass', 'ayeiugége', '32116'),
(1, 'Archibald', 'Michel', 'Michel.Archibald@gmail.com', 'Michelarch', 'azerty', '35582'),
(3, 'Blin ', 'Antoine', 'Antoine.Blin92@outlook.fr', 'Tonioblin', 'jdjdjdjjd', '23941'),
(4, 'Bombay', 'Adrien', 'Adrien.Bombay8@gmail.com', 'Bombay45', 'djdjdjgf', '34200'),
(5, 'Bordeau', 'Gwendoline', 'Gwenbord65@yahho.fr', 'Gwen46', 'djjdjdsiuy', '27970'),
(6, 'Cafeni', 'Alexis', 'Cafeni.Alex@gmail.com', 'Cafeni67', 'rkrut', '35150'),
(7, 'Chard', 'Kevin', 'Charkev@outlook.com', 'Kevinou', 'mtptpl', '35151'),
(8, 'Croitenon', 'Bryan', 'Bryancroit@wanadoo.fr', 'Bryancroi', 'totgc', '35152'),
(9, 'De Grou', 'Louis', 'DeGroulouis@gmail.com', 'Degrouis', 'rltgktrjhop', '35153'),
(10, 'De Houtri', 'Jean', 'Houtri60@wanadoo.com', 'Jean87', 'lgfkj', '35154'),
(11, 'De Madelin', 'Paul', 'DeMadPaul@hotmail.com', 'Madeline', 'fdkhoaz', '35155'),
(12, 'De Placet', 'Stanislas', 'DePlacet@yahoo.com', 'Stanplacet', 'eroihz', '35156'),
(13, 'Filo', 'Jacques', 'Jacquesfilo98@hotmail.fr', 'Ficello', 'asfoh', '35157'),
(14, 'Gap', 'David', 'Davidgapinouninet@hotmail.fr', 'Gapiou', 'asafhom', '35158'),
(15, 'Geller', 'Sarah', 'Geller@wanadoo.fr', 'Gellerer', 'djdjdjgqqte', '35159'),
(16, 'Gold', 'Ines', 'Goldmachine@orange.fr', 'Goldine', 'eeejhf', '35160'),
(17, 'Green', 'Marine', 'Greenlantern78@gmail.com', 'Green65', 'yrebs', '35161'),
(18, 'Homer', 'Théo', 'Homero@hotmail.com', 'Thomer', 'dndkf', '35162'),
(19, 'Jacqueli', 'Georges ', 'Jacqueli.Georges56@mee.fr', 'Jacqueli98', 'flezgj', '35163'),
(20, 'Jiro', 'Margaux', 'Jiraux45@gmail.com', 'Jiro3000', 'dzgjp', '35164'),
(21, 'Joi', 'Valentine', 'Joilentine@outlook.fr', 'Valou', 'mamama', '35165'),
(22, 'Kara', 'Alexia', 'Karia34@gmail.com', 'Karaté', 'kiifff', '35166'),
(23, 'Ketchum', 'Alix', 'Alix.Ketchum@outlook.fr', 'Ketchummayo', 'fheikh', '35167'),
(24, 'Koul', 'Victoire', 'Vitoirecool@wanadoo.com', 'Vicool', 'pjg', '35168'),
(25, 'Malte', 'Victoria', 'Maltoria87@hotmail.com', 'Malte67', 'pngre', '35169'),
(26, 'Molki', 'Morgane', 'Molirane@outlook.com', 'Mollki', 'djftres', '35170'),
(27, 'Molpi', 'Sasha', 'Molpisasha@outlook.fr', 'Shasha', 'detezaed', '35171'),
(28, 'Morris', 'Kenza', 'Morisenza@outlook.com', 'Morrisette', 'déeùhi', '35172'),
(29, 'Nimr', 'Mohamed', 'Nimramed@mee.fr', 'Momo76', 'zhie', '35173'),
(30, 'Pape', 'Caroline', 'Caroline.Pape@outlook.com', 'Papine', 'tutukro', '35174'),
(31, 'Patio', 'Diane', 'Dianepatio45@mee.com', 'Patio45', 'mtlryry', '35175'),
(32, 'Petra', 'Ingrid', 'IngridPetra@gmail.com', 'PetraGala', 'keagrml', '35176'),
(33, 'Pitbull', 'Adele', 'Adelitpull@outlook.com', 'Pitbull', 'ndvjirg', '35177'),
(34, 'Pizzo', 'Antoine', 'Pizzoine56@outlook.com', 'Pizzoiolo', 'vnejfi', '35178'),
(35, 'Pouil', 'Alexandre', 'PouilAlexandre@gmail.com', 'Pouillu56', 'cdnjger', '35179'),
(36, 'Poutro', 'Bertrand', 'Bertro@outlook.com', 'Poutrotri', 'fritjo', '35180'),
(37, 'Raclette', 'Dimitri', 'Dimitri.Raclette@outlook.fr', 'Raclette200', 'gehqgrg', '35181'),
(38, 'Red', 'Arnaud', 'Redarnaud@yahoo.fr', 'Redarnaud', 'grpjq', '35182'),
(39, 'Richard', 'Myriam', 'Richyriam98@wanadoo.com', 'Richiam', 'fgdnkjl', '35183'),
(40, 'Rizla', 'Edouard', 'Rizladouard@hotmail.com', 'Rizla45', 'jnkazg', '35184'),
(41, 'Roaldes', 'Alexandra', 'Roaldesandra45@gmail.com', 'Rorodra', 'gfnae', '35185'),
(42, 'Saphire', 'Flore', 'Sapire.Flore356@gmail.com', 'Saphira', 'grajkgr', '35186'),
(43, 'Scoffield', 'Raphaelle', 'Raphaellescof34@yahoo.fr', 'Scoffield', 'njknbnv', '35187'),
(44, 'Trara', 'Raphael', 'Traraphael@wanadoo.fr', 'Traratro', 'bdvnef', '35188'),
(45, 'Tribiane', 'Michelle', 'Michelletribiane@gmail.com', 'Tribiane45', 'fdgjdgtrr', '35189'),
(46, 'Troh', 'Hortense', 'Hortensetrohtroh12@gmail.com', 'Annetrotro', 'sfnsfknf', '35190'),
(47, 'Truelle', 'Christophe', 'Turelleistophe@wanadoo.com', 'degrouis', 'dkngdg', '35191'),
(48, 'Urtira', 'Charlotte', 'UrtiraCharlotte@wanadoo.com', 'Urtira56', 'bvcbcbcb', '35192'),
(49, 'Vilmer', 'Charles', 'Charles.vil@hotmail.com', 'Vilmerarles', 'efjthet', '35193'),
(50, 'Winston', 'Fabien', 'WinstonFab45@hotmail.fr', 'Winstonblue', 'fjengeg', '35194');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
